target 'RxStateExample' do
  platform :ios, '10.0'
  use_frameworks!

  # Pods for RxStateExample
  pod 'RxDataSources', '1.0.3'
  pod 'R.swift', '3.2.0'
  pod 'RxState', :path => '../'
  pod 'RxOptional', '3.1.3'

  target 'RxStateExampleTests' do
    inherit! :search_paths

  end

  target 'RxStateExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
