def common_pods
    pod 'RxState', :path => "../"
    pod 'RxSwift', '~>5.1'
    pod 'RxCocoa', '~>5.1'
    pod 'RxOptional', '~>4.1'
end

def common_test_pods
    pod 'RxTest', '~>5.1'
end


target 'RxStateExample-iOS' do
  platform :ios, '9.0'
  use_frameworks!

  pod 'RxDataSources', '~>4.0'
  common_pods
end

target 'RxStateExample-macOS' do
  platform :osx, '10.10'
  use_frameworks!
  common_pods
end

target 'RxStateExampleTests' do
    platform :ios, '9.0'
    use_frameworks!
    common_pods
    common_test_pods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxSwift'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
end
